version: '3.9'

services:

  db:

    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - production_db_volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=ytc_backend
      - MYSQL_ROOT_PASSWORD=example